org: gersonmlb
app: reto-backend
service: reto-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:330883926333:table/PlanetsTable
        - arn:aws:dynamodb:us-east-1:330883926333:table/SpeciesPlanet
        - arn:aws:dynamodb:us-east-1:330883926333:table/TablaPlanetas

plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-dynamodb-local

package:
    individually: true

custom:
    tableName: TablaPlanetas
    bucketName: myserverlessretobackend-123123
    dynamodb:
        stages:
            - dev
        start:
            port: 8000
            inMemory: true
            migrate: true
        migration:
            dir: offline

functions:
  planets:
    handler: api/planets/v1/getPlanets.getPlanets
    events:
      - httpApi:
          path: /api/v1/planets
          method: get

  getPlanet:
    handler: api/planets/v2/getPlanet.getPlanet
    events:
      - httpApi:
          path: /api/v2/planets/{id}
          method: get

  addPlanet:
    handler: api/planets/v2/addPlanet.add
    events:
      - httpApi:
          path: /api/v2/addplanet
          method: post
  
  getSpecie:
    handler: api/species/v1/getSpecie.getSpecie
    events:
      - httpApi:
          path: /api/v2/specie/{id}
          method: get

resources:
  Resources:
    PlanetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PlanetsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    TablaPlanetas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaPlanetas
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    
    SpeciesPlanet:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SpeciesPlanet
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
